# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x07\n\x05\x45mpty\"<\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1c\n\x08Username\x12\x10\n\x08username\x18\x01 \x01(\t\"*\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"3\n\x08Response\x12\x0f\n\x07retType\x18\x01 \x01(\x05\x12\x16\n\x0eresponseString\x18\x02 \x01(\t\"\x1a\n\tListQuery\x12\r\n\x05query\x18\x01 \x01(\t2\x91\x02\n\nChatServer\x12\x1b\n\x04Ping\x12\x06.Empty\x1a\t.Response\"\x00\x12\x1e\n\x08Register\x12\x05.User\x1a\t.Response\"\x00\x12\x1b\n\x05Login\x12\x05.User\x1a\t.Response\"\x00\x12 \n\x06Logout\x12\t.Username\x1a\t.Response\"\x00\x12 \n\x07SendMsg\x12\x08.Message\x1a\t.Response\"\x00\x12\x1f\n\x04List\x12\n.ListQuery\x1a\t.Response\"\x00\x12 \n\x06\x44\x65lete\x12\t.Username\x1a\t.Response\"\x00\x12\"\n\x07GetMsgs\x12\t.Username\x1a\x08.Message\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=14
  _EMPTY._serialized_end=21
  _MESSAGE._serialized_start=23
  _MESSAGE._serialized_end=83
  _USERNAME._serialized_start=85
  _USERNAME._serialized_end=113
  _USER._serialized_start=115
  _USER._serialized_end=157
  _RESPONSE._serialized_start=159
  _RESPONSE._serialized_end=210
  _LISTQUERY._serialized_start=212
  _LISTQUERY._serialized_end=238
  _CHATSERVER._serialized_start=241
  _CHATSERVER._serialized_end=514
# @@protoc_insertion_point(module_scope)
